---
# tasks file for sample-mysql
- name: create partition
  community.general.parted:
    device: /dev/sdb
    number: 1
    flags: [ lvm ]
    state: present
    part_end: 800MB

- name: create vg_database
  community.general.lvg:
    vg: vg_database
    pvs: /dev/sdb1

- name: create lv_mysql
  community.general.lvol:
    vg: vg_database
    lv: lv_mysql
    size: 512M

- name: format
  community.general.filesystem:
    fstype: xfs
    dev: /dev/mapper/vg_database-lv_mysql

- name: create mount folder
  ansible.builtin.file:
    state: directory
    path: /mnt/mysql_backups

- name: fstab
  ansible.posix.mount:
    path: /mnt/mysql_backups
    src: /dev/mapper/vg_database-lv_mysql
    fstype: xfs
    state: mounted



