---
- hosts: database
  become: true
  tasks:
    - name: Create folder
      ansible.builtin.file:
        state: directory
        path: /etc/ansible/facts.d

    - name: Set facts
      ansible.builtin.copy:
        content: |
          [sample_exam]
          server_role=mysql
        dest: /etc/ansible/facts.d/custom.fact
 
# Validate with 'ansible database -m setup -a "filter=ansible_local"'
