---
- hosts: proxy
  become: true
  tasks:
    - name: create log file
      ansible.builtin.file:
        state: touch
        path: /var/log/time.log

    - name: manage crontab
      ansible.builtin.cron:
        name: "time.log"
        minute: "0"
        hour: "*"
        job: "echo $(date) >> /var/log/time.log"

      
