---
- hosts: all
  become: true
  tasks:
    - name: Add multiple repositories into the same file (1/2)
      ansible.builtin.yum_repository:
        name: BaseOS
        description: BaseOs on repo.ansi.example.com
        file: rpms
        baseurl: http://repo.ansi.example.com/BaseOS
        gpgcheck: no

    - name: Add multiple repositories into the same file (2/2)
      ansible.builtin.yum_repository:
        name: AppStream
        description: AppStream on repo.ansi.example.com
        file: rpms
        baseurl: http://repo.ansi.example.com/AppStream
        gpgcheck: no

    - name: Disable repo
      ansible.builtin.lineinfile:
        path: /etc/yum.repos.d/ipa.repo
        regexp: '^enabled=1'
        line: enabled=0

