---
- hosts: localhost
  become: true

# From /usr/share/ansible/collections/ansible_collections/redhat/rhel_system_roles/docs/selinux/selinux-playbook.yml

  vars:
    selinux_booleans:
      - name: httpd_can_network_connect
        state: true
        persistent: true
  tasks:
    - name: Execute the role and reboot in a rescue block
      block:
        - name: Include selinux role
          include_role:
            name: redhat.rhel_system_roles.selinux
      rescue:
        - name: >-
            Fail if failed for a different reason than selinux_reboot_required
          fail:
            msg: "role failed"
          when: not selinux_reboot_required

        - name: Restart managed host
          reboot:

        - name: Wait for managed host to come back
          wait_for_connection:
            delay: 10
            timeout: 300

        - name: Reapply the role
          include_role:
            name: redhat.rhel_system_roles.selinux
