---
- hosts: all
  become: true
  tasks:
    - name: more than 512mb of ram
    # ansible-galaxy collection install community.posix
      ansible.posix.sysctl :
        name: vm.swappiness
        value: 10
        state: present
        reload: yes
      when: ansible_facts['memtotal_mb'] >= 512

    - name: more than 512mb of ram
      ansible.builtin.debug:
        msg: "Server memory less than 512MB"
      when: ansible_memtotal_mb < 512

